[build]
builder = "RAILPACK"
buildCommand = "npm install --include=dev && npm run build"

[deploy]
startCommand = "npm run start -- --hostname 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
